"""Class labels and text prompts used by CLIP and YOLO."""

ROOM_LABELS = [
    "sala",
    "cocina",
    "dormitorio",
    "bano",
    "comedor",
    "lavanderia",
    "balcon",
    "terraza",
    "gimnasio",
    "exterior",
    "area_trabajo",
    "patio_jardin",
    "estacionamiento",
    "pasadizo",
    "recepcion",
    "walking_closet",
    "piscina",
]

DISPLAY_LABELS = {
    "sala": "sala",
    "cocina": "cocina",
    "dormitorio": "dormitorio",
    "bano": "baño",
    "comedor": "comedor",
    "lavanderia": "lavandería",
    "balcon": "balcón",
    "terraza": "terraza",
    "gimnasio": "gimnasio",
    "exterior": "exterior",
    "area_trabajo": "área de trabajo",
    "patio_jardin": "patio/jardín",
    "estacionamiento": "estacionamiento",
    "pasadizo": "pasadizo/corredor",
    "recepcion": "recepción",
    "walking_closet": "walking closet",
    "piscina": "piscina",
}

ENGLISH_LABELS = {
    "sala": "living room or event hall",
    "cocina": "kitchen",
    "dormitorio": "bedroom",
    "bano": "bathroom",
    "comedor": "dining room",
    "lavanderia": "laundry room",
    "balcon": "balcony",
    "terraza": "terrace or rooftop",
    "gimnasio": "gym or fitness room",
    "exterior": "outdoor or exterior view",
    "area_trabajo": "office or workspace",
    "patio_jardin": "patio or garden",
    "estacionamiento": "parking or garage",
    "pasadizo": "hallway or corridor",
    "recepcion": "reception or lobby",
    "walking_closet": "walk-in closet or dressing room",
    "piscina": "swimming pool",
}

ZERO_SHOT_PROMPTS = {
    label: f"a photo of a {english_label} in a real estate listing"
    for label, english_label in ENGLISH_LABELS.items()
}

# YOLO furniture detection classes
FURNITURE_CLASSES = [
    "bed",
    "chair",
    "sofa",
    "table",
    "lamp",
    "closet",
    "curtain",
    "shelf",
    "plant",
    "ottoman",
    "wardrobe",
    "desk",
    "cabinet",
    "tv",
    "rug",
    "pillow",
    "door",
    "window",
    "clock",
    "sink",
    "toilet",
    "refrigerator",
    "stove",
    "vase",
]

FURNITURE_DISPLAY_NAMES = {
    "bed": "cama",
    "chair": "silla",
    "sofa": "sofá",
    "table": "mesa",
    "lamp": "lámpara",
    "closet": "armario",
    "curtain": "cortina",
    "shelf": "estante",
    "plant": "planta",
    "ottoman": "puf",
    "wardrobe": "armario",
    "desk": "escritorio",
    "cabinet": "gabinete",
    "tv": "televisor",
    "rug": "alfombra",
    "pillow": "almohada",
    "door": "puerta",
    "window": "ventana",
    "clock": "reloj",
    "sink": "lavabo",
    "toilet": "inodoro",
    "refrigerator": "refrigerador",
    "stove": "cocina",
    "vase": "jarrón",
}
